# Generated by Django 5.1.3 on 2024-11-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_instructor_fitnessclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
