# Generated by Django 5.1.3 on 2024-11-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_instructor_fitnessclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.fitnessclass')),
            ],
        ),
    ]
