# Generated by Django 5.1.3 on 2024-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
