# Generated by Django 5.1.3 on 2024-11-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_fitnessclass_fee'),
        ('fitness', '0004_fitnessclass_price_delete_booking'),
    ]

    operations = [
    ]
